---
- hosts: all
  #vars:
         #ansible_python_interpreter: "/usr/bin/python3"
  tasks:
    - name: copy-file
      copy: src=./deploy.sh dest=/tmp/deploy.sh
      
    - name: Atributo
      shell: chmod +x /tmp/deploy.sh

    - name: start config
      shell: /tmp/deploy.sh
