---
- hosts: all
  
  #vars:
         #ansible_python_interpreter: "/usr/bin/python3"
  
  tasks:
  
      - name: "Instalando docker"
        shell: sudo yum install docker -y
        
      - name: Install docker-compose
        shell: sudo curl -L https://github.com/docker/compose/releases/download/1.21.0/docker-compose-`uname -s`-`uname -m` | sudo tee /usr/local/bin/docker-compose > /dev/null

      - name: "Config docker-compose"
        shell: sudo chmod +x /usr/local/bin/docker-compose
        
      - name: "Instalando docker-compose"
       shell: sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
        
      - name: "Iniciando servico do docker"
        shell: sudo systemctl start docker
      
      - name: "Configurando docker no boot do SO"
        shell: sudo systemctl enable docker
